# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lahgolz
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-project

stages:
  default:
    params:
      tableName: "memes-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [MemesTable, Arn]
  environment:
    MEMES_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    MemesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
    MemesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: memes-bucket

plugins:
  - serverless-offline
  - serverless-dynamodb
  - serverless-s3-local

custom:
  serverless-dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
  s3:
    host: localhost
    directory: /tmp
